import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#a44100',
        background: '#f8f9ff',
        'on-tertiary-fixed-variant': '#7b2f00',
        'on-error': '#ffffff',
        'primary-fixed-dim': '#c3c0ff',
        'tertiary-fixed': '#ffdbcc',
        'surface-container': '#e5eeff',
        'surface-tint': '#4d44e3',
        'surface-container-low': '#eff4ff',
        'secondary-fixed': '#acedff',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed-variant': '#004e5c',
        'tertiary-fixed-dim': '#ffb695',
        'on-error-container': '#93000a',
        tertiary: '#7e3000',
        surface: '#f8f9ff',
        'on-primary-container': '#dad7ff',
        'surface-variant': '#d3e4fe',
        'secondary-container': '#57dffe',
        'secondary-fixed-dim': '#4cd7f6',
        error: '#ba1a1a',
        'primary-container': '#4f46e5',
        'on-secondary-fixed': '#001f26',
        'on-primary-fixed': '#0f0069',
        'inverse-primary': '#c3c0ff',
        'on-primary-fixed-variant': '#3323cc',
        'inverse-surface': '#213145',
        'error-container': '#ffdad6',
        'on-surface-variant': '#464555',
        'on-surface': '#0b1c30',
        'on-tertiary-fixed': '#351000',
        'surface-bright': '#f8f9ff',
        primary: '#3525cd',
        'on-secondary': '#ffffff',
        'outline-variant': '#c7c4d8',
        outline: '#777587',
        'surface-container-high': '#dce9ff',
        'on-secondary-container': '#006172',
        'surface-dim': '#cbdbf5',
        'primary-fixed': '#e2dfff',
        'on-background': '#0b1c30',
        'on-tertiary-container': '#ffd2be',
        'on-primary': '#ffffff',
        'on-tertiary': '#ffffff',
        'inverse-on-surface': '#eaf1ff',
        secondary: '#00687a',
        'surface-container-highest': '#d3e4fe',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'gutter-mobile': '16px',
        'container-max': '1440px',
        unit: '8px',
        'gutter-desktop': '24px',
        'sidebar-width': '260px',
        'margin-page': '32px',
      },
      fontFamily: {
        'headline-lg': ['Geist', 'system-ui', 'sans-serif'],
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
        'headline-md': ['Geist', 'system-ui', 'sans-serif'],
        mono: ['"Geist Mono"', 'ui-monospace', 'monospace'],
        'label-md': ['Geist', 'system-ui', 'sans-serif'],
        'body-sm': ['Inter', 'system-ui', 'sans-serif'],
        'headline-lg-mobile': ['Geist', 'system-ui', 'sans-serif'],
        display: ['Geist', 'system-ui', 'sans-serif'],
        'label-sm': ['Geist', 'system-ui', 'sans-serif'],
        'body-lg': ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['30px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        mono: ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg-mobile': [
          '24px',
          { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' },
        ],
        display: ['48px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
      keyframes: {
        'fade-in': {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.4s ease-out',
      },
    },
  },
  plugins: [],
} satisfies Config
